name: dopamine
description: Flutter (Material 3) frontend for the Dopamine jailbreak.
publish_to: "none"
version: 3.0.9

module:
  androidX: false
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
